### ISSUE TITLE
SLACK_MESSAGE is shown as null

### ISSUE THREAD

**Issue by Naoki206** [rtCamp/action-slack-notify#107]
I'm using the latest version(v2.2.0) of Slack Notify, and in the Environment Variables, I didn't set any values on the SLACK_MESSAGE as it's recommended on the docs, but it is shown as null every time.
hope it will be resolved

**Comment by Naoki206** [comment]
@mrrobot47  cc

**Comment by iarejenius** [comment]
I think I can guess what you're running into @Naoki206 since I just encountered it too.

When rtCamp/action-slack-notify [fires off a message to slack](https://github.com/rtCamp/action-slack-notify/blob/85f56f6231bc7524406b7187504eb3bc99b9d576/main.go#L203), it populates the message via an environment variable -- [SLACK_MESSAGE](https://github.com/rtCamp/action-slack-notify/blob/85f56f6231bc7524406b7187504eb3bc99b9d576/main.go#L18).

So where does that variable get set? You can see [here in the accompanying shell script](https://github.com/rtCamp/action-slack-notify/blob/070bae482b794d012d036e33165dc18d91b7c6d4/main.sh#L8) that its queried from the contents of the file specified by the path `$GITHUB_EVENT_PATH`. This in turn is a [default variable provided by GitHub](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables):
![image](https://user-images.githubusercontent.com/1031515/137817030-9ba3a82b-9a53-43f7-a1a3-f7e7525f6423.png)

What's contained in the "webhook event payload"? Well that depends on what event triggered this GitHub action! In the shell script I linked to above, you can see from the snippet `jq -r '.commits[-1].message'` that they assume the event has a property `commits` on it. Turns on out there's only one trigger event that will have this property on it: [push](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push). So if you're trigger the GitHub Action with anything besides a `push`, then you won't see a commit message come through by default. Instead you'll have to do something like override `SLACK_MESSAGE` with a value gleaned from your triggering event's set of properties (e.g. the PR title if the [triggering event was a PR](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request)).

**Comment by eljhkrr** [comment]
The [deployment payload](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#deployment) does not contain the commit message, only has the sha. The API probably changed and this package is behind. I was able to work around this limitation like this:

1. Grab the latest commit message and put it in a variable
```
- name: 'Get message'
  id: 'deploy-message'
  run: |
        echo "::set-output name=commit_msg::$(git log -1 --format=%B)"
        echo "::set-output name=commit_sha::$(git log -1 --format=%H)"
```
[Read more about outputs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs)

2. Construct SLACK_MESSAGE
```
- name: 'Slack notify'
  uses: rtCamp/action-slack-notify@v2.2.0
  env:
    SLACK_WEBHOOK: my_webhook
    SLACK_CHANNEL: my_channel
    SLACK_USERNAME: username
    SLACK_TITLE: 'Title'
    SLACK_MESSAGE: ${{ steps.deploy-message.outputs.commit_msg }}
```

I hope this helps someone.

**Comment by justisGipson** [comment]
@eljhkrr this was helpful, but I'm not getting the message. just the branch hashes...

**Comment by ltroya-as** [comment]
I am getting `null` when the action is executed in a PR. Should this [PR](https://github.com/muxinc/elements/pull/292) fix that issue?
