### ISSUE TITLE
Error sending message: Post "***": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by riteshgetsetup** [rtCamp/action-slack-notify#109]
Hello Everyone,Can anyone help me its working before but suddenly its failing & getting this error.

Error sending message: Post "***": unsupported protocol scheme ""

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

can anyone tell me what we need to be fix this above issue.

**Comment by ferny1313** [comment]
I got the same error because I try to create a App Token on Slack configuration and try to use that token as the `SLACK_WEBHOOK`.

I solved the error after installing the "Incomming Webhooks" app into my slack, [here's the link](https://home-u3d6615.slack.com/apps/A0F7XDUAZ-incoming-webhooks?tab=more_info).
After installing the app, I just select the channel and got the webhook uri

This URI need to be placed into the GitHub repo settings on the secrets section. See the [documentation](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository)

Hoping I can help somebody.

**Comment by mrrobot47** [comment]
Closing this issue as it is resolved.

**Comment by fabiosantosmovidesk** [comment]
I had the same problem in two Apps I created. I solved the problem by adding a secret variable, and adding to it the path of the webhook created in my App.
**Slack:**
        url: https://api.slack.com/apps/your-app
        Features > Incoming Webhooks > Webhook Url
**Github:**
           ![image](https://user-images.githubusercontent.com/109740333/195002137-1349059e-8bdc-47b9-8c93-f6592964b57e.png)
