### ISSUE TITLE
Avoid building the action container in every job

### ISSUE THREAD

**Issue by andreasschroth** [rtCamp/action-slack-notify#16]
First of all: Thank you for the good work here. Good job. 👍 

I'm quite new to Github Actions and would like to ask if there is any way to avoid that in every single job (we use it to send a Slack notification in the case of a faillure) the container for this Action here gets built again?

Thank you in advance.

**Comment by PaulSearcy** [comment]
I don't believe this is specific to a an action, but something you have to account for in your workflow.

https://github.community/t5/GitHub-Actions/Github-Actions-CI-CD-Need-optional-jobs/m-p/29696

**Comment by mrrobot47** [comment]
It is possible to remove container building in every action run if the action run uses a docker image published on docker hub. The docker image can then be specified in `action.yml` file of this repo to get this done.

I still have to test this out completely, but yes, instead of taking ~1-1.5m in the building of this action, it will be reduced to few seconds of docker image pull instead.

I will do this in my free time. Mostly will address back on this in a week or two.

**Comment by andreasschroth** [comment]
@mrrobot47 Thank you, that would be absolutely awesome! :+1:

**Comment by xenoterracide** [comment]
subscribed

**Comment by prologic** [comment]
@mrrobot47 How's that Docker image coming along? :)

**Comment by igorhrcek** [comment]
> @mrrobot47 How's that Docker image coming along? :)

I've forked this repo and updated the `action.yml` to use existing Docker image instead of building it every time action runs:
https://github.com/mint-hosting/action-slack-notify

**Comment by mrrobot47** [comment]
@igorhrcek thanks for testing this out.

I have also added docker image in `action.yml`

Will keep that  in sync with change in master branch for now.
Will update and maintain docker images with all the tags and switch to using GitHub tag as the docker image tag as well inside the `action.yml` so that always a stable version is fetched for the people using this action.

**Comment by mrrobot47** [comment]
Use: `rtCamp/action-slack-notify@master` to use the docker image. Takes roughly `~7-15s` to complete the job and send slack notification.

`rtCamp/action-slack-notify@master` will always contain the most recent and stable version of this action. Also, From now on, tag wise as well I will keep `action.yml` updated to use that particular tagged docker image.

**Comment by igorhrcek** [comment]
Great! That is a huge improvement.

However, you should use native JSON and YAML libraries in Go and then you can easily remove jq, python, shyml and other dependencies to bring the image size down and to lower the action execution time.
