### ISSUE TITLE
did you consider adding support for markdown

### ISSUE THREAD

**Issue by derberg** [rtCamp/action-slack-notify#67]
At the moment, to get a beautiful markdown in slack, I need to convert input first with this action https://github.com/LoveToKnow/slackify-markdown-action. My input message looks like `[${{github.event.issue.title}}](${{github.event.issue.html_url}}) \n ${{github.event.issue.body}}` so I really cannot manually make it "slack" compatible as I do not have control over issue body.

but it looks like it is a simple as adding https://github.com/jsarafajr/slackify-markdown and enabling someone to specify if they want to slackify markdown in message or not.

**Comment by mrrobot47** [comment]
Hey @derberg, that is a great suggestion. We will add native support to slackify the markdown in `SLACK_MESSAGE` if an env var like say `SLACKIFY_MARKDOWN` is set to true with the help of https://github.com/jsarafajr/slackify-markdown

PRs are welcome for this enhancement. Otherwise, I will later pick this up. But that may take some time as my schedule is packed as of now.

**Comment by derberg** [comment]
@mrrobot47 yeah, sorry but go is not on my list of skills 😄 and I've already set a workaround https://github.com/asyncapi/.github/pull/18/files#diff-1ee55436eb74158dd30293540d530e66f2179cc688feb6c365f90977bdad5d8cR20-R31 that for now is fine for me. I just wanted to drop an idea as I've spent a lot of time reviewing different slack related actions, and this action was the best one after all

**Comment by elahmo** [comment]
@mrrobot47 and updates about this?

**Comment by L0RD-ZER0** [comment]
Support for Markdown has been added by using [slackify-markdown-action](https://github.com/LoveToKnow/slackify-markdown-action.) as suggested by the OP. Use ``SLACKIFY_MARKDOWN="true"`` to enable markdown to slack-formatting conversion.
